version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network 

  backend:
    build:
      context: ./server
    container_name: backend_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app_network 

  frontend:
    build:
      context: ./client
    container_name: frontend_container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:  
